// Visibility and Erasure — A Visual Atlas of the Ilısu Dam, Hasankeyf and the Tigris Valley
// Compiled for the doctoral dissertation of Yelta Köm — Bauhaus-Universität Weimar
// Compiled 12 May 2026. Translated from Turkish original.

window.ATLAS = {
  meta: {
    title: "Visibility and Erasure",
    subtitle: "A Visual Atlas of the Ilısu Dam, Hasankeyf and the Tigris Valley",
    author: "Yelta Köm",
    institution: "Bauhaus-Universität Weimar",
    compiled: "12 May 2026",
  },

  sections: [
    { id: "01", code: "DSI_Devlet", title: "State / DSİ promotional films and renderings",
      tr: "Devlet / DSİ tanıtım filmleri ve görseller" },
    { id: "02", code: "Zeynel_Bey", title: "Zeynel Bey Tomb relocation (12 May 2017)",
      tr: "Zeynel Bey Türbesi nakli (12 Mayıs 2017)" },
    { id: "03", code: "Insaat", title: "Construction companies (Nurol, Cengiz, Er-Bu, Bresser, Andritz)",
      tr: "İnşaat şirketleri" },
    { id: "04", code: "Basin_Foto", title: "Press & wire photography (AFP, Reuters, Getty, AA, DHA)",
      tr: "Basın ve ajans fotoğrafçılığı" },
    { id: "05", code: "Depardon", title: "The Mathias Depardon case (National Geographic, May–June 2017)",
      tr: "Mathias Depardon vakası" },
    { id: "06", code: "Aktivist", title: "Activist / NGO visual production (IKHA, Hasankeyf Matters, Doğa Derneği, GegenStrömung)",
      tr: "Aktivist / STK görsel üretimi" },
    { id: "07", code: "Sanatci", title: "Artistic & cultural production (Arazi Assembly, Köm, Tan, Özmen, Tekin, film, music)",
      tr: "Sanatçı ve kültürel üretim" },
    { id: "08", code: "Akademik", title: "Academic / archaeological documentation",
      tr: "Akademik / arkeolojik belgeler" },
    { id: "09", code: "Uydu_Harita", title: "Satellite imagery & cartography (NASA, Sentinel, Google Earth)",
      tr: "Uydu görüntüsü ve kartografya" },
    { id: "10", code: "Miras", title: "Heritage documentation (Europa Nostra, ICOMOS, UNESCO)",
      tr: "Miras belgeleri" },
    { id: "11", code: "Sosyal_Medya", title: "Citizen & social-media documentation",
      tr: "Yurttaş / sosyal medya belgeleri" },
    { id: "12", code: "Sular_Altinda", title: "Post-flooding visual evidence (2019–2024)",
      tr: "Sular altında — sel sonrası kanıt" },
    { id: "13", code: "Politika", title: "Policy / legal / institutional documents",
      tr: "Politika / hukuk / kurumsal belgeler" },
    { id: "14", code: "Sergi", title: "Exhibitions & biennials",
      tr: "Sergiler ve bienaller" },
    { id: "15", code: "Tarihi", title: "Historical photography (pre-2010)",
      tr: "Tarihi fotoğraflar" },
  ],

  entries: [
    // ============ 01 DSI / STATE ============
    { section: "01", id: "1.01",
      title: "Ilısu Dam Promotional Film (original DSİ Turkish-language version)",
      title_tr: "Ilısu Barajı Tanıtım Filmi (ana DSİ orijinal video)",
      type: "Promotional film", producer: "DSİ (State Hydraulic Works)",
      date: "c. 2017–2018",
      link: "https://www.youtube.com/watch?v=op4yWkqZ3-I",
      notes: "The State Hydraulic Works' principal Turkish-language promotional film; frames the project as 'the largest hydroelectric scheme on the Tigris.'" },
    { section: "01", id: "1.02",
      title: "Ilısu Prof. Dr. Veysel Eroğlu Dam — promotional film after renaming",
      title_tr: "Ilısu Prof. Dr. Veysel Eroğlu Barajı tanıtım filmi",
      type: "Promotional film", producer: "DSİ",
      date: "2018+",
      link: "https://www.youtube.com/watch?v=OgiDJMiHvHg",
      notes: "Released after the official renaming of the dam after the former Minister Veysel Eroğlu." },
    { section: "01", id: "1.03",
      title: "Ilısu Dam and Hydroelectric Project Promotional Film, 2018",
      title_tr: "Ilısu Barajı ve HES Projesi Tanıtım Filmi 2018",
      type: "Promotional film", producer: "DSİ", date: "2018",
      link: "https://www.youtube.com/watch?v=jUwIR0zahuY",
      notes: "Locates the project at the Mardin/Şırnak provincial border, 15 km east of Dargeçit, 45 km from the Syrian border." },
    { section: "01", id: "1.04",
      title: "Artefacts to be relocated from Hasankeyf — English and Kurdish-language versions",
      title_tr: "Hasankeyf'te taşınacak eserler (İngilizce ve Kürtçe versiyonlar)",
      type: "Promotional film (multilingual)", producer: "DSİ 16th Regional Directorate (Diyarbakır)",
      date: "c. 2017",
      link: "https://t24.com.tr/haber/goruntulu-hasankeyfteki-tasinma-icin-ingilizce-ve-kurtce-tanitim-filmi,719977",
      notes: "Rare Kurdish-language release by a Turkish state institution; video embedded in T24 news report." },
    { section: "01", id: "1.05",
      title: "DSİ official website — Ilısu Project page",
      title_tr: "DSİ Resmi Web Sitesi — Ilısu Projesi sayfası",
      type: "Institutional page", producer: "DSİ", date: "continuously updated",
      link: "https://www.dsi.gov.tr/",
      notes: "DSİ technical reports and photographs. Search keyword: 'Ilısu'." },
    { section: "01", id: "1.06",
      title: "Ilısu Dam drone footage (AA wire)",
      title_tr: "Ilısu Barajı drone görüntüleri (AA wire)",
      type: "Drone B-roll", producer: "Anadolu Agency / DSİ",
      date: "2019–2020",
      link: "https://www.aa.com.tr/tr/arama?s=ilisu+baraji",
      notes: "Footage recycled in news coverage of the dam's commissioning." },
    { section: "01", id: "1.07",
      title: "Erdoğan–Eroğlu opening ceremony, Ilısu Dam (19 May 2020)",
      title_tr: "Erdoğan–Eroğlu Ilısu Barajı açılışı",
      type: "Official ceremony photo", producer: "Presidency of Turkey (TCCB)",
      date: "19 May 2020",
      link: "https://www.tccb.gov.tr/haberler/arama/?q=ilisu",
      notes: "Official Presidency news archive — search: 'Ilısu Barajı'." },
    { section: "01", id: "1.08",
      title: "New Hasankeyf — promotional imagery",
      title_tr: "Yeni Hasankeyf — tanıtım/promosyonel görüntüler",
      type: "Promotional photo/video", producer: "Hasankeyf District Governorship / TOKİ",
      date: "2010s",
      link: "http://www.hasankeyf.gov.tr/",
      notes: "District-governorship and Ministry of Culture pages." },
    { section: "01", id: "1.09",
      title: "KUVAM Cultural Heritage Action Plan (2008) — reference document",
      title_tr: "KUVAM Kültürel Miras Eylem Planı (2008)",
      type: "Architectural plan report", producer: "KUVAM / DSİ",
      date: "2008",
      link: "https://www.proculther.eu/wp-content/uploads/2021/03/Cengiz-Eruzun-et-al.-Conservation-and-Salvage-Project-of-the-Zeynel-Bey-Tomb.pdf",
      notes: "Cited extensively in PROCULTHER PDF; master plan for the relocation of eight monuments." },
    { section: "01", id: "1.10",
      title: "DSİ Survey and Planning Department — Hasankeyf studies archive",
      title_tr: "DSİ Etüd ve Plan Dairesi — Hasankeyf çalışmaları arşivi",
      type: "Plan / project imagery", producer: "DSİ Survey Department",
      date: "1997–2018",
      link: "https://www.dsi.gov.tr/Sayfa/Detay/745",
      notes: "DSİ publications section; report PDFs include visual material." },
    { section: "01", id: "1.11",
      title: "Hasankeyf Excavation Project — official site",
      title_tr: "Hasankeyf Kazıları resmi sitesi",
      type: "Excavation photo archive", producer: "KUVAM / METU / Mardin Artuklu University",
      date: "2004–2019",
      link: "https://hasankeyfexcavations.com/",
      notes: "Zeynel Bey complex documented: 3 madrasas, 1 zawiya, 1 mausoleum, 1 caravanserai, 1 hammam." },
    { section: "01", id: "1.12",
      title: "Veysel Eroğlu's visit to Hasankeyf (2 June 2017)",
      title_tr: "Veysel Eroğlu Hasankeyf ziyareti (2 Haziran 2017)",
      type: "Ministerial visit photos", producer: "Ministry press / Diken news",
      date: "2 Jun 2017",
      link: "https://www.diken.com.tr/eroglundan-hasankeyfte-dinamit-aciklamasi/",
      notes: "Eroğlu's remarks defending the use of dynamite during demolition." },
    { section: "01", id: "1.13",
      title: "Ilısu HEPP turbine commissioning (19 May 2020)",
      title_tr: "Ilısu HES Türbin Devreye Alma",
      type: "Industrial ceremony photo", producer: "DSİ",
      date: "19 May 2020",
      link: "https://www.dsi.gov.tr/Haber",
      notes: "Official announcement of first turbine commissioning (link approximate — search DSİ news archive)." },
    { section: "01", id: "1.14",
      title: "Hasankeyf Cultural Park (New Hasankeyf) — official promotion",
      title_tr: "Hasankeyf Kültür Parkı — resmi tanıtım",
      type: "Park promotion", producer: "Ministry of Culture and Tourism",
      date: "2020+",
      link: "https://batman.ktb.gov.tr/",
      notes: "Ministry provincial pages; new location of the relocated monuments." },
    { section: "01", id: "1.15",
      title: "DSİ 16th Regional Directorate (Diyarbakır) — news archive",
      title_tr: "DSİ 16. Bölge Müdürlüğü Diyarbakır — haber arşivi",
      type: "Institutional news / photo", producer: "DSİ Diyarbakır",
      date: "ongoing",
      link: "https://bolge16.dsi.gov.tr/",
      notes: "Diyarbakır Regional Directorate; Hasankeyf / Ilısu updates." },

    // ============ 02 ZEYNEL BEY ============
    { section: "02", id: "2.HDR-A", header: "A — State imagery" },
    { section: "02", id: "2.01",
      title: "AFP wire video of the Zeynel Bey Tomb relocation (original)",
      title_tr: "Zeynel Bey Türbesi naklinin AFP wire video",
      type: "News video", producer: "AFP / DHA / Reuters",
      date: "12 May 2017",
      link: "https://www.afp.com/en/news-hub",
      notes: "Primary wire video of the tomb on a wheeled platform; AA and DHA versions also circulated worldwide." },
    { section: "02", id: "2.02",
      title: "National Geographic embedded video of the Zeynel Bey relocation",
      title_tr: "Zeynel Bey naklinin National Geographic videosu",
      type: "News video + photo essay", producer: "National Geographic",
      date: "May 2017",
      link: "https://www.nationalgeographic.com/history/article/turkey-dam-tomb-zeynel-bey-hasankeyf",
      notes: "Includes engineer Ahmet Turer's commentary; the 'tomb on wheels' was disseminated globally." },
    { section: "02", id: "2.03",
      title: "Reuters photo gallery of the relocation",
      title_tr: "Türbenin Reuters foto galerisi",
      type: "Photo gallery", producer: "Reuters / Stringer",
      date: "12 May 2017",
      link: "https://www.reuters.com/article/idUSKBN1881OY/",
      notes: "Reuters news text plus six or more photographs; rights via Reuters Pictures." },
    { section: "02", id: "2.04",
      title: "Anadolu Agency (AA) photo set of the relocation",
      title_tr: "AA Zeynel Bey nakli fotoğraf seti",
      type: "Wire photo", producer: "AA staff photographer",
      date: "12 May 2017",
      link: "https://www.aa.com.tr/tr/arama?s=zeynel+bey",
      notes: "Dated entry in AA archive; high-resolution stills accompany news text." },
    { section: "02", id: "2.05",
      title: "The tomb on its wheeled platform — Hürriyet front page",
      title_tr: "Türbenin tekerlekli platform üzerinde — Hürriyet kapak",
      type: "Newspaper photo / cover", producer: "Hürriyet",
      date: "13 May 2017",
      link: "https://www.hurriyet.com.tr/gundem/zeynel-bey-turbesi-tasindi-40459889",
      notes: "Hürriyet web archive; print masthead included." },
    { section: "02", id: "2.06",
      title: "DHA video of the relocation",
      title_tr: "DHA naklin video kaynağı",
      type: "Video", producer: "DHA (Demirören News Agency)",
      date: "12 May 2017",
      link: "https://www.youtube.com/@DHAHaber",
      notes: "DHA YouTube channel; search required." },
    { section: "02", id: "2.07",
      title: "PROCULTHER engineering documentation (full PDF)",
      title_tr: "PROCULTHER mühendislik belgeleri (tam PDF)",
      type: "Engineering report + photographs",
      producer: "Er-Bu / KUVAM engineers (Cengiz Eruzun et al.)",
      date: "2017–2018",
      link: "https://www.proculther.eu/wp-content/uploads/2021/03/Cengiz-Eruzun-et-al.-Conservation-and-Salvage-Project-of-the-Zeynel-Bey-Tomb.pdf",
      notes: "Technical diagrams, hydraulic system details, before/after photographs." },
    { section: "02", id: "2.08",
      title: "'Conservation and Salvage Project of the Zeynel Bey Tomb' — academic paper",
      title_tr: "Akademik makale — Eruzun et al.",
      type: "Academic article + photos", producer: "Cengiz Eruzun et al.",
      date: "2017",
      link: "https://www.proculther.eu/wp-content/uploads/2021/03/Cengiz-Eruzun-et-al.-Conservation-and-Salvage-Project-of-the-Zeynel-Bey-Tomb.pdf",
      notes: "Downloadable PDF including KUVAM engineering photographs." },
    { section: "02", id: "2.09",
      title: "The tomb at its new location (Hasankeyf Cultural Park)",
      title_tr: "Türbenin yeni konumunda — Hasankeyf Kültür Parkı",
      type: "Completion photo", producer: "DSİ / Ministry of Culture",
      date: "mid-2017+",
      link: "https://commons.wikimedia.org/wiki/Category:Zeynel_Bey_Mausoleum",
      notes: "Wikimedia Commons — licensed photographs at new location." },
    { section: "02", id: "2.HDR-B", header: "B — Counter-images: NGO and activist documentation" },
    { section: "02", id: "2.10",
      title: "Photographs of the tomb being encased in concrete",
      title_tr: "Türbenin beton içine alınması fotoğrafları",
      type: "Activist photo set", producer: "Initiative to Keep Hasankeyf Alive (IKHA)",
      date: "10–11 May 2017",
      link: "https://www.hasankeyfgirisimi.net/",
      notes: "Frames the same object not as 'preservation' but as 'destruction'." },
    { section: "02", id: "2.11",
      title: "Hasankeyf Matters — counter-report on the tomb relocation",
      title_tr: "Hasankeyf Matters — Türbe nakli karşı raporu",
      type: "Photo + analysis", producer: "Hasankeyf Matters (John Crofoot)",
      date: "Feb 2017",
      link: "https://hasankeyfmatters.com/2017/02/19/the-fate-of-the-zeynel-bey-tomb/",
      notes: "Densely photo-documented counter-argument; Crofoot's most comprehensive essay on the case." },
    { section: "02", id: "2.12",
      title: "OECD-NCP complaint against Bresser",
      title_tr: "OECD-NCP Bresser şikayet dosyası",
      type: "Legal document + photo", producer: "OECD Watch / IKHA / FIVAS / Hasankeyf Matters",
      date: "Aug 2018",
      link: "https://www.oecdwatch.org/complaint/hasankeyf-matters-fivas-iniative-to-keep-hasankeyf-alive-and-both-ends-vs-bresser-eurasia/",
      notes: "Official OECD Watch case page; final decision of the Dutch NCP." },
    { section: "02", id: "2.13",
      title: "Riverwatch commentary on the postponement demand",
      title_tr: "Riverwatch zorunlu erteleme yorumu",
      type: "Analysis + photo", producer: "Ulrich Eichelmann / Riverwatch",
      date: "May 2017",
      link: "https://www.riverwatch.eu/en/hasankeyf",
      notes: "On the same day: the tomb was relocated and Depardon was detained — an activist framing." },
    { section: "02", id: "2.14",
      title: "Open letter: 'Halt the tomb relocation'",
      title_tr: "Açık mektup — 'Türbe naklini durdurun'",
      type: "Campaign document", producer: "Hasankeyf Matters + 50+ academics",
      date: "Dec 2016",
      link: "https://hasankeyfmatters.com/",
      notes: "References Korres Engineering and Bresser." },
    { section: "02", id: "2.15",
      title: "ANF News — 'Tomb to be moved tomorrow'",
      title_tr: "ANF News haberi",
      type: "News video / photo", producer: "ANF (Ajansa Nûçeyên Firatê)",
      date: "11 May 2017",
      link: "https://anfenglish.com/news/",
      notes: "Kurdish-press perspective; technical detail." },
    { section: "02", id: "2.16",
      title: "Diken — 'Dynamite-grade explosives are damaging the natural fabric'",
      title_tr: "Diken — dinamit açıklaması",
      type: "Photo-news", producer: "Diken / IKHA statement",
      date: "Jun 2017",
      link: "https://www.diken.com.tr/eroglundan-hasankeyfte-dinamit-aciklamasi/",
      notes: "IKHA statement following Eroğlu's visit." },
    { section: "02", id: "2.17",
      title: "Bianet — critique of the tomb's new location",
      title_tr: "Bianet — yeni konum eleştirisi",
      type: "News + photo", producer: "Bianet",
      date: "2017",
      link: "https://bianet.org/haber/hasankeyf-i-yasatma-girisimi-konuyu-takip-edecegiz-186455",
      notes: "Calls for a referendum; sets out alternative proposals." },

    // ============ 03 CONSTRUCTION ============
    { section: "03", id: "3.01",
      title: "Nurol İnşaat — corporate page, Ilısu project reference",
      type: "Institutional project page", producer: "Nurol İnşaat", date: "2010s",
      link: "https://www.nurol.com.tr/" },
    { section: "03", id: "3.02",
      title: "Cengiz Holding — Ilısu HEPP project",
      type: "Corporate PR", producer: "Cengiz İnşaat", date: "2010s",
      link: "https://www.cengiz.com.tr/" },
    { section: "03", id: "3.03",
      title: "Çelikler Holding — corporate",
      type: "Institutional", producer: "Çelikler Holding", date: "2010s",
      link: "https://celiklerholding.com.tr/" },
    { section: "03", id: "3.04",
      title: "Andritz Hydro — press releases",
      type: "Press release + photo", producer: "Andritz AG, Graz", date: "2010s",
      link: "https://www.andritz.com/group-en/media-center/press-releases" },
    { section: "03", id: "3.05",
      title: "Temelsu International — engineering design",
      type: "Engineering plan", producer: "Temelsu International", date: "design 1997–2006",
      link: "https://www.temelsu.com.tr/" },
    { section: "03", id: "3.06",
      title: "Er-Bu İnşaat — principal contractor for the Zeynel Bey relocation",
      type: "Company archive", producer: "Er-Bu İnşaat (Ankara)", date: "2016–2017",
      link: "https://www.erbu.com.tr/" },
    { section: "03", id: "3.07",
      title: "Bresser Eurasia (Netherlands) — hydraulic lifting",
      type: "Engineering firm page", producer: "Bresser BV / Eurasia", date: "2016–2017",
      link: "https://www.bresser.eu/en/" },
    { section: "03", id: "3.08",
      title: "Korres Engineering (Greece)",
      type: "Engineering firm page", producer: "Korres Engineering, Athens", date: "2016",
      link: "https://www.korresengineering.com/" },
    { section: "03", id: "3.09",
      title: "Ilısu Consortium — Va Tech Hydro / Andritz prior to withdrawal",
      type: "General sector", producer: "Va Tech Hydro (Austria/Switzerland)", date: "2006–2009",
      link: "https://www.andritz.com/" },
    { section: "03", id: "3.10",
      title: "Sümerbank / Eti Maden and other state stakeholders",
      type: "Institutional", producer: "Republic of Turkey", date: "2010s",
      link: "https://www.csb.gov.tr/" },
    { section: "03", id: "3.11",
      title: "BBC News — 'Insurers halt work on Turkish dam' (ECA withdrawal)",
      type: "News + photo", producer: "BBC", date: "24 Dec 2008",
      link: "https://news.bbc.co.uk/2/hi/business/7798292.stm" },
    { section: "03", id: "3.12",
      title: "Berne Declaration / Public Eye — Ilısu financing report",
      type: "Independent expert report", producer: "Public Eye (Berne Declaration)", date: "2007–2009",
      link: "https://www.publiceye.ch/en/topics/development-finance/case-study-ilisu-dam-turkey" },

    // ============ 04 PRESS PHOTOGRAPHY ============
    { section: "04", id: "4.01",
      title: "Bülent Kılıç — 40-file archive, pre-submersion Hasankeyf",
      type: "Photo-essay (40+ images)", producer: "Bülent Kılıç (AFP)", date: "AFP",
      link: "https://www.gettyimages.com/photos/hasankeyf?photographer=B%C3%9CLENT+KILI%C3%87",
      notes: "Getty Images archive — editorial; filter on 'Hasankeyf'." },
    { section: "04", id: "4.02",
      title: "Aerial view of Ilısu Dam — 199 villages submerged",
      type: "Drone photo", producer: "Bülent Kılıç (likely)", date: "AFP",
      link: "https://www.gettyimages.com/photos/ilisu-dam",
      notes: "AFP / Getty drone editorial." },
    { section: "04", id: "4.03",
      title: "'People visit the small ancient town of Hasankeyf' — last visitors before submersion",
      type: "Editorial photo", producer: "Bülent Kılıç (AFP)", date: "AFP",
      link: "https://www.gettyimages.com/photos/hasankeyf",
      notes: "The last tourists taking selfies." },
    { section: "04", id: "4.04",
      title: "El-Rızk Mosque minaret — before submersion",
      type: "Editorial photo", producer: "Bülent Kılıç", date: "AFP/Getty",
      link: "https://www.gettyimages.com/photos/el-rizk-mosque",
      notes: "The most circulated post-flooding image." },
    { section: "04", id: "4.05",
      title: "Reuters — 'History disappears as dam waters flood ancient Turkish town' photo set",
      type: "Wire photo set", producer: "Sertaç Kayar (Reuters)", date: "Reuters",
      link: "https://www.reuters.com/article/world/history-disappears-as-dam-waters-flood-ancient-turkish-town-idUSKBN20Q1H4/",
      notes: "Reuters Pictures archive; multiple photographs." },
    { section: "04", id: "4.06",
      title: "Burak Kara / Getty — Hasankeyf submersion editorial",
      type: "Editorial photo", producer: "Burak Kara (Getty Images)", date: "Getty Images",
      link: "https://www.gettyimages.com/photos/hasankeyf-burak-kara",
      notes: "Getty archive; Hasankeyf filter." },
    { section: "04", id: "4.07",
      title: "Burak Kara — submersion image used in LifeGate feature",
      type: "Editorial photo", producer: "Burak Kara", date: "Getty / LifeGate",
      link: "https://www.lifegate.com/ercan-ayboga-hasankeyf-ilisu-dam",
      notes: "Feature interview with Ercan Ayboğa." },
    { section: "04", id: "4.08",
      title: "Hürriyet — Hasankeyf newspaper archive",
      type: "Newspaper photo archive", producer: "Various correspondents", date: "Hürriyet",
      link: "https://www.hurriyet.com.tr/haberleri/hasankeyf",
      notes: "Mainstream Turkish-press perspective." },
    { section: "04", id: "4.09",
      title: "Cumhuriyet — critical Hasankeyf reporting",
      type: "Newspaper archive", producer: "Various", date: "Cumhuriyet",
      link: "https://www.cumhuriyet.com.tr/haberler/hasankeyf",
      notes: "Critical Turkish-language coverage." },
    { section: "04", id: "4.10",
      title: "BirGün — critical Hasankeyf coverage",
      type: "Newspaper archive", producer: "Various", date: "BirGün",
      link: "https://www.birgun.net/arama/?q=hasankeyf",
      notes: "Turkish-left perspective." },
    { section: "04", id: "4.11",
      title: "Evrensel — Hasankeyf tag",
      type: "Newspaper archive", producer: "Various", date: "Evrensel",
      link: "https://www.evrensel.net/haber-arama?q=hasankeyf",
      notes: "Turkish-left coverage." },
    { section: "04", id: "4.12",
      title: "Bianet English — Hasankeyf archive",
      type: "Independent news archive", producer: "Various", date: "Bianet",
      link: "https://bianet.org/english/search?q=hasankeyf",
      notes: "English-language; independent press." },
    { section: "04", id: "4.13",
      title: "T24 — Hasankeyf archive (incl. English/Kurdish promo coverage)",
      type: "News archive", producer: "Various", date: "T24",
      link: "https://t24.com.tr/etiket/hasankeyf",
      notes: "T24 tag page." },
    { section: "04", id: "4.14",
      title: "ANF News (Kurdish news agency) — Hasankeyf English-language archive",
      type: "News archive", producer: "ANF (Ajansa Nûçeyên Firatê)", date: "2010s",
      link: "https://anfenglish.com/search/news?text=hasankeyf" },
    { section: "04", id: "4.15",
      title: "Mesopotamia News Agency (MHA) — Hasankeyf tag",
      type: "News archive", producer: "MHA", date: "2017+",
      link: "https://mezopotamyaajansi.com/" },
    { section: "04", id: "4.16",
      title: "Yeni Yaşam newspaper — Hasankeyf coverage",
      type: "News / photo", producer: "Various", date: "Yeni Yaşam",
      link: "https://yeniyasamgazetesi2.com/",
      notes: "Kurdish/left perspective." },
    { section: "04", id: "4.17",
      title: "Smithsonian Magazine — 'Endangered Site: The City of Hasankeyf'",
      type: "Photo-essay", producer: "Andrew Curry; photos by Images & Stories / Alamy",
      date: "Smithsonian",
      link: "https://www.smithsonianmag.com/travel/endangered-cultural-treasures-hasankeyf-15292683/",
      notes: "Major pre-submersion photo essay." },
    { section: "04", id: "4.18",
      title: "The Atlantic — 'Moving an Ancient Town to Higher Ground'",
      type: "Photo-essay (Alan Taylor)", producer: "Various wire photographers", date: "The Atlantic",
      link: "https://www.theatlantic.com/photo/2019/10/photos-moving-ancient-town-higher-ground/599698/",
      notes: "Edited by Alan Taylor; multiple photo sources." },
    { section: "04", id: "4.19",
      title: "France 24 Observers — 'Turkish authorities demolish market in 12,000-year-old village'",
      type: "Photo-news + civic video", producer: "Rıdvan Ayhan (local) + Observers team",
      date: "France 24",
      link: "https://observers.france24.com/en/20191125-turkey-hasankeyf-market-demolish-ilisu-dam",
      notes: "Embeds Rıdvan Ayhan's Facebook video." },
    { section: "04", id: "4.20",
      title: "BBC News — Hasankeyf and Ilısu coverage",
      type: "TV news + photo", producer: "BBC team", date: "BBC",
      link: "https://www.bbc.com/news/world-europe-49810912",
      notes: "Major 2019 report." },
    { section: "04", id: "4.21",
      title: "DW (Deutsche Welle) — Hasankeyf documentary coverage",
      type: "Documentary / photo", producer: "DW team", date: "DW",
      link: "https://www.dw.com/en/turkey-hasankeyf-ilisu-dam/a-52465960",
      notes: "English and German versions." },
    { section: "04", id: "4.22",
      title: "The Guardian — Hasankeyf photo story",
      type: "Photo-essay", producer: "Various", date: "The Guardian",
      link: "https://www.theguardian.com/world/2019/oct/09/hasankeyf-turkey-ilisu-dam",
      notes: "Major pre-submersion report." },
    { section: "04", id: "4.23",
      title: "The New York Times — 'Save Hasankeyf' coverage",
      type: "News archive", producer: "Various", date: "New York Times",
      link: "https://www.nytimes.com/search?query=hasankeyf",
      notes: "NYT search; multiple articles." },
    { section: "04", id: "4.24",
      title: "Le Monde — coverage",
      type: "News archive", producer: "Various", date: "Le Monde",
      link: "https://www.lemonde.fr/recherche/?search_keywords=hasankeyf",
      notes: "French-language archive; includes Depardon case." },
    { section: "04", id: "4.25",
      title: "Al Jazeera English — Hasankeyf documentary and news",
      type: "Documentary + news", producer: "Al Jazeera team", date: "Al Jazeera",
      link: "https://www.aljazeera.com/search/hasankeyf",
      notes: "English-language coverage." },
    { section: "04", id: "4.26",
      title: "Yusuf Yavuz (Odatv) — investigative journalism",
      type: "Photo-news archive", producer: "Yusuf Yavuz", date: "Odatv",
      link: "https://odatv4.com/yusuf-yavuz",
      notes: "Turkish-language reporting drawn from local sources." },
    { section: "04", id: "4.27",
      title: "soL News — 'Hasankeyf historic bazaar evacuated; shopkeeper sets own shop on fire'",
      type: "Photo", producer: "soL", date: "soL Haber",
      link: "https://haber.sol.org.tr/turkiye/hasankeyf-tarihi-carsi-bosaltildi-esnaf-dukkanini-yakti-272985",
      notes: "Shopkeeper resistance (image available in project knowledge base PDF)." },
    { section: "04", id: "4.28",
      title: "Yasin Akgül / AFP — Depardon solidarity photo",
      type: "Editorial archive", producer: "Yasin Akgül", date: "AFP",
      link: "https://www.gettyimages.com/photos/yasin-akgul",
      notes: "Solidarity in front of the Istanbul Governor's Residence." },

    // ============ 05 DEPARDON ============
    { section: "05", id: "5.01",
      title: "Depardon's last photograph before detention — Malabadi Bridge",
      title_tr: "Tutuklanmadan önceki son fotoğraf",
      type: "Editorial photo", producer: "Mathias Depardon", date: "May 2017",
      link: "https://www.mathiasdepardon.com/" },
    { section: "05", id: "5.02",
      title: "National Geographic — 'Turkey releases photographer' (return statement)",
      type: "Editorial news", producer: "National Geographic", date: "Jun 2017",
      link: "https://www.nationalgeographic.com/" },
    { section: "05", id: "5.03",
      title: "British Journal of Photography — Depardon dossier",
      type: "Editorial archive", producer: "BJP / 1854 Photography", date: "May–Jun 2017",
      link: "https://www.1854.photography/" },
    { section: "05", id: "5.04",
      title: "'Mathias Depardon released by Turkish government' — BJP",
      type: "News", producer: "BJP", date: "9 Jun 2017",
      link: "https://www.1854.photography/2017/06/mathias-depardon-released-turkish-government/" },
    { section: "05", id: "5.05",
      title: "France 24 — 'French photographer freed from Turkish jail'",
      type: "News", producer: "France 24", date: "9 Jun 2017",
      link: "https://www.france24.com/en/20170609-french-photographer-freed-turkish-jail-depardon" },
    { section: "05", id: "5.06",
      title: "ANF News — 'National Geographic photographer detained in Hasankeyf'",
      type: "News", producer: "ANF", date: "8 May 2017",
      link: "https://anfenglish.com/" },
    { section: "05", id: "5.07",
      title: "Pro Photo Daily — 'Calls for release of Mathias Depardon'",
      type: "Editorial article", producer: "AI-AP", date: "May 2017",
      link: "https://www.aiap.org/" },
    { section: "05", id: "5.08",
      title: "RSF (Reporters Without Borders) — call for Depardon's release",
      type: "Civil-society call", producer: "RSF", date: "May 2017",
      link: "https://rsf.org/en/news?keys=depardon" },
    { section: "05", id: "5.09",
      title: "EFJ joint appeal",
      type: "Civil society", producer: "European Federation of Journalists", date: "9 Jun 2017",
      link: "https://europeanjournalists.org/" },
    { section: "05", id: "5.10",
      title: "CPJ (Committee to Protect Journalists) — Depardon dossier",
      type: "Civil society", producer: "CPJ", date: "May 2017",
      link: "https://cpj.org/data/people/mathias-depardon/" },
    { section: "05", id: "5.11",
      title: "IKHA — statement on Depardon's detention",
      type: "NGO statement", producer: "Initiative to Keep Hasankeyf Alive", date: "May 2017",
      link: "https://www.hasankeyfgirisimi.net/" },
    { section: "05", id: "5.12",
      title: "Mathias Depardon — personal site, Hasankeyf work",
      type: "Artist site", producer: "Mathias Depardon", date: "ongoing",
      link: "https://www.mathiasdepardon.com/" },
    { section: "05", id: "5.13",
      title: "Turkish Minute — Bülent Kılıç dismissed from AFP (related press-freedom case)",
      type: "News", producer: "Turkish Minute", date: "26 Mar 2024",
      link: "https://www.turkishminute.com/2024/03/26/bulent-kilic-fired-afp/" },

    // ============ 06 ACTIVIST / NGO ============
    { section: "06", id: "6.HDR-A", header: "A — Initiative to Keep Hasankeyf Alive (IKHA)" },
    { section: "06", id: "6.01",
      title: "IKHA main site — 15+ years of campaign archive",
      type: "NGO archive", producer: "Initiative to Keep Hasankeyf Alive", date: "2006–present",
      link: "https://www.hasankeyfgirisimi.net/" },
    { section: "06", id: "6.02",
      title: "IKHA English-language mirror site",
      type: "NGO archive", producer: "IKHA", date: "ongoing",
      link: "https://www.hasankeyfgirisimi.net/?lang=en" },
    { section: "06", id: "6.03",
      title: "IKHA on Twitter / X — @hasankeyfdicle",
      type: "Social-media archive", producer: "IKHA", date: "2010s",
      link: "https://x.com/hasankeyfdicle" },
    { section: "06", id: "6.04",
      title: "IKHA on Facebook — hasankeyfyasatmagirisimi",
      type: "Social-media archive", producer: "IKHA", date: "2010s",
      link: "https://www.facebook.com/hasankeyfyasatmagirisimi" },
    { section: "06", id: "6.05",
      title: "'Hasankeyf Lied in Hamburg' — solidarity video",
      type: "Petition + poster", producer: "IKHA + Hamburg solidarity group", date: "2010s",
      link: "https://www.youtube.com/results?search_query=hasankeyf+hamburg" },
    { section: "06", id: "6.06",
      title: "Urgent international appeal — 'Save Hasankeyf!'",
      type: "Civil-society call", producer: "IKHA", date: "2019",
      link: "https://www.hasankeyfgirisimi.net/?p=1832" },
    { section: "06", id: "6.07",
      title: "Hasankeyf solidarity concert — Grup Gerduni",
      type: "Concert video", producer: "IKHA / Istanbul Avcılar", date: "2019",
      link: "https://www.youtube.com/results?search_query=hasankeyf+gerduni" },
    { section: "06", id: "6.08",
      title: "Hasankeyf–Tigris Big Jump — annual event",
      type: "Event photo", producer: "IKHA / European river protection network", date: "2010s",
      link: "https://www.bigjump.org/" },
    { section: "06", id: "6.09",
      title: "Ercan Ayboğa profile (Bauhaus-Weimar alumnus, IKHA coordinator)",
      type: "Biography + photo", producer: "LifeGate / Ercan Ayboğa", date: "2020",
      link: "https://www.lifegate.com/ercan-ayboga-hasankeyf-ilisu-dam" },
    { section: "06", id: "6.HDR-B", header: "B — Hasankeyf Matters (John Crofoot)" },
    { section: "06", id: "6.10",
      title: "Hasankeyf Matters — main site",
      type: "English-language advocacy", producer: "John Crofoot et al.", date: "2010s–2020",
      link: "https://hasankeyfmatters.com/" },
    { section: "06", id: "6.11",
      title: "'Saving Hasankeyf' — Critical Muslim article (image-rich)",
      type: "Photo-essay / academic", producer: "John Crofoot", date: "c. 2016",
      link: "https://www.criticalmuslim.io/saving-hasankeyf/" },
    { section: "06", id: "6.12",
      title: "'Saving Hasankeyf' on Academia.edu (PDF with photographs)",
      type: "Academic PDF", producer: "John Crofoot", date: "c. 2016",
      link: "https://www.academia.edu/" },
    { section: "06", id: "6.HDR-C", header: "C — Doğa Derneği / BirdLife Turkey" },
    { section: "06", id: "6.13",
      title: "Doğa Derneği — Hasankeyf and Tigris Valley campaign page",
      type: "NGO campaign page", producer: "Doğa Derneği", date: "2005+",
      link: "https://www.dogadernegi.org/hasankeyf/" },
    { section: "06", id: "6.14",
      title: "DogaVision YouTube channel",
      type: "Video archive", producer: "Doğa Derneği", date: "ongoing",
      link: "https://www.youtube.com/@dogavision" },
    { section: "06", id: "6.15",
      title: "Tarkan at Hasankeyf — UNESCO petition media event",
      type: "Photo-event", producer: "Doğa Derneği + Tarkan", date: "2008",
      link: "https://www.youtube.com/results?search_query=tarkan+hasankeyf" },
    { section: "06", id: "6.16",
      title: "'The Hasankeyf Campaign and Doğa Derneği' — interview/video",
      type: "Video", producer: "Derya Engin / Doğa Derneği", date: "2010s",
      link: "https://www.youtube.com/@dogavision" },
    { section: "06", id: "6.17",
      title: "Ahunbay & Balkız — 'Outstanding Universal Value of Hasankeyf' report",
      type: "Academic report + photo", producer: "Z. Ahunbay (İTÜ), Ö. Balkız (Doğa Derneği)", date: "2009",
      link: "https://www.academia.edu/" },
    { section: "06", id: "6.HDR-D", header: "D — GegenStrömung / CounterCurrent (Germany)" },
    { section: "06", id: "6.18",
      title: "GegenStrömung — main site, Ilısu category",
      type: "NGO archive (German)", producer: "CounterCurrent–GegenStrömung", date: "2010s",
      link: "https://www.gegenstroemung.org/web/" },
    { section: "06", id: "6.19",
      title: "'Hasankeyf and the Tigris — unique worldwide' — report",
      type: "Photo-report", producer: "GegenStrömung", date: "2019",
      link: "https://www.gegenstroemung.org/web/wp-content/uploads/2019/06/Hasankeyf-Report-2019.pdf" },
    { section: "06", id: "6.20",
      title: "'VerDammte Dämme' (Damned Dams) — documentary film",
      type: "Documentary", producer: "GegenStrömung", date: "14 Mar 2018",
      link: "https://www.gegenstroemung.org/web/" },
    { section: "06", id: "6.HDR-E", header: "E — Manfred-Hermsen-Stiftung (Bremen)" },
    { section: "06", id: "6.21",
      title: "'Stop Ilisu — Save Hasankeyf!' project page",
      type: "NGO campaign", producer: "Manfred-Hermsen-Stiftung", date: "2010s",
      link: "https://www.m-h-s.org/en/stop-ilisu-save-hasankeyf" },
    { section: "06", id: "6.22",
      title: "'We have all lost — Hasankeyf is sinking' — photo-essay",
      type: "Photo-essay", producer: "Ulrich Eichelmann / MHS", date: "Oct 2019",
      link: "https://www.m-h-s.org/en/we-have-all-lost-hasankeyf-is-sinking" },
    { section: "06", id: "6.23",
      title: "Council of Europe Cultural Heritage Sub-Committee — site visits Dec 2007 / Aug 2008",
      type: "Independent expert report + photo", producer: "Council of Europe", date: "2008",
      link: "https://www.m-h-s.org/" },
    { section: "06", id: "6.HDR-F", header: "F — Other international coalitions" },
    { section: "06", id: "6.24",
      title: "Riverwatch — Hasankeyf, Eichelmann's farewell article",
      type: "NGO photo", producer: "Riverwatch / EuroNatur", date: "2019–2020",
      link: "https://www.riverwatch.eu/en/hasankeyf" },
    { section: "06", id: "6.25",
      title: "Riverwatch — tomb relocation + Depardon",
      type: "NGO archive", producer: "Riverwatch", date: "May 2017",
      link: "https://www.riverwatch.eu/en/hasankeyf" },
    { section: "06", id: "6.26",
      title: "Save the Tigris Foundation — Europa Nostra announcement",
      type: "Civil society", producer: "Save the Tigris (ICSSI)", date: "2016",
      link: "https://www.savethetigris.org/" },
    { section: "06", id: "6.27",
      title: "FIVAS (Norway) — co-complainant in the OECD case",
      type: "NGO archive", producer: "FIVAS", date: "2017–2018",
      link: "https://www.fivas.org/" },
    { section: "06", id: "6.28",
      title: "The Corner House (UK) — Ilısu financing reports",
      type: "Critical report", producer: "The Corner House", date: "2000s",
      link: "https://www.thecornerhouse.org.uk/" },
    { section: "06", id: "6.29",
      title: "Public Eye (Berne Declaration) — Ilısu reports",
      type: "Independent expert", producer: "Public Eye / Berne Declaration", date: "2007+",
      link: "https://www.publiceye.ch/" },
    { section: "06", id: "6.30",
      title: "ECA-Watch Austria — Ulrich Eichelmann coordination",
      type: "NGO archive", producer: "ECA-Watch Austria", date: "2010s",
      link: "https://www.eca-watch.org/" },
    { section: "06", id: "6.31",
      title: "Mesopotamia Ecology Movement (MEM) document — Komün Akademi",
      type: "Activist analysis", producer: "MEM / Ercan Ayboğa", date: "Apr 2020",
      link: "https://komunakademi.com/" },
    { section: "06", id: "6.32",
      title: "Compagnie Bien à vous — performance at the Vatican",
      type: "Performance video / photo", producer: "RojInfo / Compagnie Bien à vous — Armanc Kerborani",
      date: "27 Jul 2019",
      link: "https://rojinfo.com/" },
    { section: "06", id: "6.33",
      title: "TMMOB Chamber of Architects — statements on Hasankeyf",
      type: "Institutional opinion + photo", producer: "TMMOB", date: "2010s",
      link: "https://www.mimarlarodasi.org.tr/" },

    // ============ 07 ARTIST / CULTURAL ============
    { section: "07", id: "7.HDR-A", header: "A — Yelta Köm" },
    { section: "07", id: "7.01",
      title: "Yelta Köm — personal archive site",
      type: "Artist site", producer: "Yelta Köm", date: "ongoing",
      link: "https://www.yeltakom.com/" },
    { section: "07", id: "7.02",
      title: "'Lines of Displacement: Along the Tigris' (with Agit Özdemir)",
      type: "Moving image + counter-mapping", producer: "Yelta Köm + Agit Özdemir", date: "2022–",
      link: "https://www.yeltakom.com/lines-of-displacement" },
    { section: "07", id: "7.03",
      title: "Spore Initiative Berlin — 'Lines of Displacement' workshop",
      type: "Workshop + presentation", producer: "Yelta Köm + Agit Özdemir / Spore Initiative", date: "2024",
      link: "https://spore-initiative.org/en/events/lines-of-displacement" },
    { section: "07", id: "7.04",
      title: "'Resisting Against Ecocide: Remapping Hasankeyf and the Tigris' — Vienna",
      type: "Conference / installation", producer: "Yelta Köm / Arazi Assembly", date: "Nov 2024",
      link: "https://www.akbild.ac.at/" },
    { section: "07", id: "7.05",
      title: "Köm — Bauhaus-Weimar künstlergespräch",
      type: "Lecture (documented)", producer: "Yelta Köm / Bauhaus-Univ. Weimar", date: "2024",
      link: "https://www.uni-weimar.de/" },
    { section: "07", id: "7.HDR-B", header: "B — Arazi Assembly (Mardin, 2014–)" },
    { section: "07", id: "7.06",
      title: "Arazi Assembly — main site, team and projects",
      type: "Artist collective archive", producer: "Arazi Assembly", date: "2014–",
      link: "https://araziassembly.org/" },
    { section: "07", id: "7.07",
      title: "'State of Displacement: Entangled Topographies' — 17th Istanbul Biennial",
      type: "Mixed-media installation", producer: "Arazi Assembly + Topological Atlas",
      date: "17 Sep – 20 Nov 2022",
      link: "https://17b.iksv.org/" },
    { section: "07", id: "7.08",
      title: "Arazi Assembly + Topological Atlas — public online seminars (2021)",
      type: "Seminar archive", producer: "Awan, Tan, Sharma, Aydoğdu et al.", date: "2021",
      link: "https://topologicalatlas.net/seminars" },
    { section: "07", id: "7.09",
      title: "Padlet seminar archive — 2021",
      type: "Online archive", producer: "Arazi Assembly + Topological Atlas", date: "2021",
      link: "https://padlet.com/" },
    { section: "07", id: "7.10",
      title: "XXI Magazine — 'On Survival Methodologies' (on Arazi Assembly)",
      type: "Critical writing", producer: "XXI Magazine", date: "2022",
      link: "https://xximagazine.com/" },
    { section: "07", id: "7.HDR-C", header: "C — Pelin Tan / Topological Atlas" },
    { section: "07", id: "7.11",
      title: "Topological Atlas — main site (TU Delft / Goldsmiths)",
      type: "ERC project site", producer: "Nishat Awan (PI), Yelta Köm, Pelin Tan et al.",
      date: "2018–",
      link: "https://topologicalatlas.net/" },
    { section: "07", id: "7.12",
      title: "Topological Atlas — project blog",
      type: "Online archive", producer: "Topological Atlas team", date: "2019+",
      link: "https://topologicalatlas.net/blog" },
    { section: "07", id: "7.13",
      title: "'Gilgamesh: She Who Saw the Deep' (Pelin Tan + Anton Vidokle)",
      type: "Film", producer: "Pelin Tan + Anton Vidokle, score by Alva Noto", date: "2022",
      link: "https://www.e-flux.com/video/gilgamesh-she-who-saw-the-deep" },
    { section: "07", id: "7.14",
      title: "Pelin Tan — e-flux survey (with Magnus Ericson)",
      type: "Online interview", producer: "e-flux", date: "2022",
      link: "https://www.e-flux.com/journal/" },
    { section: "07", id: "7.15",
      title: "Pelin Tan — 'State of Displacement' curatorial text (Academia.edu)",
      type: "Online essay + photo", producer: "Pelin Tan", date: "2022",
      link: "https://www.academia.edu/" },
    { section: "07", id: "7.16",
      title: "Pelin Tan — 'Field as Entanglement and Transversal Methodology'",
      type: "Gallery PDF", producer: "Pelin Tan / Topological Atlas", date: "2019",
      link: "https://topologicalatlas.net/" },
    { section: "07", id: "7.HDR-D", header: "D — Diyarbakır art scene (Özmen, Tekin, Altındere, Özgen)" },
    { section: "07", id: "7.17",
      title: "Şener Özmen — CV and work archive (Pilevneli)",
      type: "Artist site", producer: "Şener Özmen / Pilevneli Gallery", date: "ongoing",
      link: "https://pilevneli.com/artists/sener-ozmen" },
    { section: "07", id: "7.18",
      title: "Şener Özmen — Art21 'Turkish and Other Delights'",
      type: "Artist interview", producer: "Art21 Magazine", date: "Jun 2011",
      link: "https://magazine.art21.org/" },
    { section: "07", id: "7.19",
      title: "'Road to Tate Modern / Tate'e Giden Yol' — video (Özmen + Özgen)",
      type: "Video / land-art piece", producer: "Şener Özmen + Erkan Özgen", date: "2003",
      link: "https://www.youtube.com/results?search_query=road+to+tate+modern" },
    { section: "07", id: "7.20",
      title: "Cengiz Tekin — Art21 profile",
      type: "Artist interview", producer: "Art21 Magazine", date: "Jul 2011",
      link: "https://magazine.art21.org/" },
    { section: "07", id: "7.21",
      title: "Cengiz Tekin — 'Yol' (2023), Artforum review",
      type: "Critical article + photo", producer: "Cengiz Tekin / Artforum", date: "2023",
      link: "https://www.artforum.com/" },
    { section: "07", id: "7.22",
      title: "Hyperallergic — 'The Diyarbakır Art Scene and the Voice of Kurdish Resistance'",
      type: "Critical writing", producer: "Hyperallergic", date: "2020s",
      link: "https://hyperallergic.com/" },
    { section: "07", id: "7.23",
      title: "Şener Özmen — Sanatatak interview: 'Shouting can be a good start'",
      type: "Conversation", producer: "Sanatatak", date: "2010s",
      link: "https://www.sanatatak.com/" },
    { section: "07", id: "7.HDR-E", header: "E — Music and performance" },
    { section: "07", id: "7.24",
      title: "Aynur Doğan — 'Rewend' (dedicated to Hasankeyf), directed by Fatih Akın",
      type: "Music video", producer: "Aynur Doğan / Fatih Akın", date: "2010s",
      link: "https://www.youtube.com/results?search_query=aynur+rewend" },
    { section: "07", id: "7.25",
      title: "Aynur Doğan — official site",
      type: "Artist site", producer: "Aynur Doğan", date: "ongoing",
      link: "https://www.aynurdogan.net/" },
    { section: "07", id: "7.26",
      title: "Compagnie Bien à vous — Vatican performance, full report",
      type: "Performance / photo / video", producer: "RojInfo / Armanc Kerborani", date: "27 Jul 2019",
      link: "https://rojinfo.com/" },
    { section: "07", id: "7.HDR-F", header: "F — Documentary / film" },
    { section: "07", id: "7.27",
      title: "'Death History of Water' / 'Heskîf' — documentary search",
      type: "Documentary", producer: "Ali Ergül / Elif Yiğit", date: "2019–2020",
      link: "https://www.youtube.com/results?search_query=heskif+suyun+olum+tarihi" },
    { section: "07", id: "7.28",
      title: "'VerDammte Dämme' (Damned Dams) — on GegenStrömung",
      type: "Documentary", producer: "GegenStrömung", date: "Mar 2018",
      link: "https://www.gegenstroemung.org/" },
    { section: "07", id: "7.29",
      title: "Can Candan — 'Documentary Cinema and Resistance in Turkey', book chapter",
      type: "Academic chapter", producer: "Can Candan", date: "2015",
      link: "https://www.academia.edu/" },

    // ============ 08 ACADEMIC ============
    { section: "08", id: "8.01",
      title: "Hasankeyf Excavations — official site",
      type: "Archaeological documentation", producer: "KUVAM / METU / Mardin Artuklu",
      date: "2004–2019",
      link: "https://hasankeyfexcavations.com/" },
    { section: "08", id: "8.02",
      title: "'Hasankeyf, the Ilısu Dam, and Common European Standards'",
      type: "Academic article", producer: "Alessandro Chechi et al.", date: "2018",
      link: "https://www.academia.edu/" },
    { section: "08", id: "8.03",
      title: "Bahar Aykan — 'From Living in History to Ghost Town: Hasankeyf's Lost Social Values'",
      type: "Academic + photo", producer: "Bahar Aykan", date: "n.d.",
      link: "https://www.academia.edu/" },
    { section: "08", id: "8.04",
      title: "Cengiz Eruzun et al. — 'Conservation and Salvage of the Zeynel Bey Tomb'",
      type: "Academic article (PDF on project page)", producer: "Cengiz Eruzun et al.", date: "2017",
      link: "https://www.proculther.eu/wp-content/uploads/2021/03/Cengiz-Eruzun-et-al.-Conservation-and-Salvage-Project-of-the-Zeynel-Bey-Tomb.pdf" },
    { section: "08", id: "8.05",
      title: "Morvaridi — 'Resettlement, Rights to Development and the Ilısu Dam'",
      type: "Academic article", producer: "B. Morvaridi", date: "2004",
      link: "https://www.tandfonline.com/" },
    { section: "08", id: "8.06",
      title: "Akıncı & Tan — 'climates_waterdam' (PDF in project knowledge base)",
      type: "Academic article", producer: "Akıncı, Tan", date: "n.d.",
      link: "https://topologicalatlas.net/" },
    { section: "08", id: "8.07",
      title: "'Hidden Treasure of the Tigris: The Ilısu Dam' (state-academic publication)",
      type: "State academic publication", producer: "Academics commissioned by DSİ", date: "n.d.",
      link: "https://www.dsi.gov.tr/" },
    { section: "08", id: "8.08",
      title: "Pınar Aykaç — 'Absent Presents: musealisation of Hasankeyf'",
      type: "Academic + photo", producer: "Pınar Aykaç", date: "n.d.",
      link: "https://www.academia.edu/" },
    { section: "08", id: "8.09",
      title: "Ahunbay & Balkız — UNESCO Outstanding Universal Value report",
      type: "Independent expert report", producer: "Z. Ahunbay (İTÜ), Ö. Balkız", date: "2009",
      link: "https://www.academia.edu/" },
    { section: "08", id: "8.10",
      title: "Albert Gabriel — 'Voyages archéologiques dans la Turquie Orientale' (1940)",
      type: "Historical archaeological publication", producer: "Albert Gabriel", date: "1940",
      link: "https://archive.org/" },
    { section: "08", id: "8.11",
      title: "'Yesterday and Today' — Hypotheses blog, Hasankeyf academic literature",
      type: "Academic blog", producer: "Hypotheses.org academic blogs", date: "2010s",
      link: "https://hypotheses.org/" },
    { section: "08", id: "8.13",
      title: "Mardin Artuklu University — Leyla Keskin MA thesis, 'Ecological Mourning'",
      type: "MA thesis", producer: "Leyla Keskin / Mardin Artuklu", date: "2022",
      link: "https://tez.yok.gov.tr/" },
    { section: "08", id: "8.14",
      title: "Council of Europe — 'Cultural Aspects of the Ilısu Dam Project, Turkey'",
      type: "Parliamentary report", producer: "Council of Europe", date: "18 Dec 2001",
      link: "https://assembly.coe.int/" },
    { section: "08", id: "8.15",
      title: "Council of Europe — Sub-Committee on Cultural Heritage, December 2007 visit report",
      type: "Parliamentary report", producer: "Council of Europe (for Hermes/OeKB/SERV)", date: "4 Feb 2008",
      link: "https://www.m-h-s.org/" },
    { section: "08", id: "8.16",
      title: "Council of Europe — Sub-Committee, August 2008 visit report",
      type: "Parliamentary report", producer: "Council of Europe", date: "20 Oct 2008",
      link: "https://www.m-h-s.org/" },

    // ============ 09 SATELLITE / MAPS ============
    { section: "09", id: "9.01",
      title: "NASA Earth Observatory — 'Slowly Flooding History' (22 Feb 2019 vs 12 Mar 2020)",
      type: "Landsat 8 OLI image pair", producer: "NASA / Kasha Patel", date: "13 Mar 2020",
      link: "https://earthobservatory.nasa.gov/images/146449/slowly-flooding-history" },
    { section: "09", id: "9.02",
      title: "Landsat Image Gallery — the same image, high-resolution",
      type: "Landsat 8 downloadable TIFF", producer: "NASA", date: "2020",
      link: "https://landsat.visibleearth.nasa.gov/" },
    { section: "09", id: "9.03",
      title: "International Business Times — Landsat image republished, 17 Mar 2020",
      type: "Landsat 8 image + analysis", producer: "IBTimes / NASA EO", date: "17 Mar 2020",
      link: "https://www.ibtimes.com/" },
    { section: "09", id: "9.04",
      title: "ESA Copernicus Sentinel-2 — Hasankeyf region (open access)",
      type: "Sentinel-2 multi-spectral image", producer: "ESA Copernicus", date: "2018–present",
      link: "https://browser.dataspace.copernicus.eu/" },
    { section: "09", id: "9.05",
      title: "ESA Sentinel-1 SAR — Ilısu region (for subsidence / phantom infrastructure)",
      type: "Sentinel-1 SAR", producer: "ESA Copernicus", date: "2014–present",
      link: "https://browser.dataspace.copernicus.eu/" },
    { section: "09", id: "9.06",
      title: "Google Earth — Hasankeyf historical-imagery timeline",
      type: "Historical satellite imagery slider", producer: "Google / Maxar", date: "2005–present",
      link: "https://earth.google.com/web/" },
    { section: "09", id: "9.07",
      title: "Google Maps — current view of Hasankeyf",
      type: "Online map", producer: "Google Maps", date: "current",
      link: "https://maps.google.com/?q=Hasankeyf" },
    { section: "09", id: "9.08",
      title: "NASA Earth Observatory — 'Reservoir Swells Upstream of Mosul' (downstream effects)",
      type: "Landsat", producer: "NASA", date: "2019",
      link: "https://earthobservatory.nasa.gov/" },
    { section: "09", id: "9.09",
      title: "Wikipedia — Ilısu Dam infographic map",
      type: "Schematic map", producer: "Wikipedia / sourced from DSİ", date: "current",
      link: "https://en.wikipedia.org/wiki/Il%C4%B1su_Dam" },
    { section: "09", id: "9.10",
      title: "Wikimedia Commons — 'Hasankeyf' category (hundreds of licensed images)",
      type: "Crowd-sourced photo archive", producer: "Wikimedia users", date: "2005–present",
      link: "https://commons.wikimedia.org/wiki/Category:Hasankeyf" },
    { section: "09", id: "9.11",
      title: "Wikimedia Commons — 'Ilısu Dam' category",
      type: "Photo archive", producer: "Wikimedia", date: "2010s",
      link: "https://commons.wikimedia.org/wiki/Category:Il%C4%B1su_Dam" },
    { section: "09", id: "9.12",
      title: "Wikimedia Commons — 'Zeynel Bey Mausoleum' category",
      type: "Photo archive", producer: "Wikimedia", date: "2017+",
      link: "https://commons.wikimedia.org/wiki/Category:Zeynel_Bey_Mausoleum" },
    { section: "09", id: "9.13",
      title: "USGS EarthExplorer — full Landsat time series",
      type: "Multi-sensor satellite archive", producer: "USGS / NASA", date: "1972–present",
      link: "https://earthexplorer.usgs.gov/" },
    { section: "09", id: "9.14",
      title: "Maxar / Planet Labs — commercial high-resolution",
      type: "Commercial satellite (licensed)", producer: "Maxar Technologies / Planet Labs", date: "current",
      link: "https://www.maxar.com/" },

    // ============ 10 HERITAGE ============
    { section: "10", id: "10.01",
      title: "Europa Nostra — '7 Most Endangered 2016', Hasankeyf profile",
      type: "Official heritage dossier + photo", producer: "Europa Nostra", date: "2016",
      link: "https://www.europanostra.org/heritage_alerts/hasankeyf-and-its-surroundings-turkey/" },
    { section: "10", id: "10.02",
      title: "Europa Nostra — '14 European heritage sites shortlisted 2016' announcement",
      type: "Press release + photo", producer: "Europa Nostra", date: "10 Dec 2015",
      link: "https://www.europanostra.org/" },
    { section: "10", id: "10.03",
      title: "Europa Nostra — 'Europe's 7 Most Endangered 2016 announced'",
      type: "Press release", producer: "Europa Nostra", date: "16 Mar 2016",
      link: "https://www.europanostra.org/" },
    { section: "10", id: "10.04",
      title: "Europa Nostra Board statement on Hasankeyf (after the tomb relocation)",
      type: "Official statement", producer: "Europa Nostra Board", date: "14 May 2017",
      link: "https://www.europanostra.org/" },
    { section: "10", id: "10.05",
      title: "Europa Nostra — 'It's not too late to save Hasankeyf!'",
      type: "Press release + photo", producer: "Europa Nostra / Athens board", date: "Jun 2019",
      link: "https://www.europanostra.org/" },
    { section: "10", id: "10.06",
      title: "Bianet English — Europa Nostra's listing of Hasankeyf",
      type: "News", producer: "Bianet", date: "16 Mar 2016",
      link: "https://bianet.org/english/" },
    { section: "10", id: "10.07",
      title: "Council of Europe — Cultural Aspects Report, 2001",
      type: "Parliamentary report", producer: "Council of Europe PACE", date: "18 Dec 2001",
      link: "https://assembly.coe.int/" },
    { section: "10", id: "10.08",
      title: "UNESCO WHC — Türkiye Tentative List (Hasankeyf absent)",
      type: "UNESCO database", producer: "UNESCO World Heritage Centre", date: "current",
      link: "https://whc.unesco.org/en/statesparties/tr" },
    { section: "10", id: "10.09",
      title: "ICOMOS Türkiye — statements on Hasankeyf",
      type: "Professional opinion", producer: "ICOMOS Türkiye", date: "2010s",
      link: "https://www.icomos.org.tr/" },
    { section: "10", id: "10.10",
      title: "World Monuments Fund — Hasankeyf historical reports",
      type: "Heritage organisation", producer: "WMF", date: "2000s",
      link: "https://www.wmf.org/" },
    { section: "10", id: "10.11",
      title: "Kültür Bilincini Geliştirme Vakfı (KBGV) — Europa Nostra dossier",
      type: "Nomination dossier + photo", producer: "KBGV / Istanbul", date: "2015",
      link: "https://kbgvakfi.com.tr/" },

    // ============ 11 SOCIAL MEDIA ============
    { section: "11", id: "11.01",
      title: "Rıdvan Ayhan — Facebook video, bulldozer in the historic bazaar",
      type: "Citizen video", producer: "Rıdvan Ayhan (Hasankeyf resident)", date: "4 Nov 2019",
      link: "https://www.facebook.com/" },
    { section: "11", id: "11.02",
      title: "Hasankeyf shopkeeper setting his own shop on fire — video (Twitter)",
      type: "Citizen video", producer: "Anonymous shopkeeper, witness: Murat Takin", date: "10 Nov 2019",
      link: "https://twitter.com/search?q=hasankeyf%20esnaf%20yakti" },
    { section: "11", id: "11.03",
      title: "#SaveHasankeyf — hashtag archive (Twitter)",
      type: "Hashtag archive", producer: "Multiple users", date: "2017+",
      link: "https://twitter.com/search?q=%23SaveHasankeyf" },
    { section: "11", id: "11.04",
      title: "#HasankeyfYaşasın — hashtag archive",
      type: "Hashtag archive (Turkish)", producer: "Multiple users", date: "2017+",
      link: "https://twitter.com/search?q=%23HasankeyfYa%C5%9Fas%C4%B1n" },
    { section: "11", id: "11.05",
      title: "#IlısuBarajı — hashtag archive",
      type: "Hashtag (counter-state)", producer: "Multiple users", date: "2010s",
      link: "https://twitter.com/search?q=%23Il%C4%B1suBaraj%C4%B1" },
    { section: "11", id: "11.06",
      title: "#HasankeyfÖlüyor — hashtag",
      type: "Hashtag archive", producer: "Activists", date: "2019–2020",
      link: "https://twitter.com/search?q=%23Hasankeyf%C3%96l%C3%BCyor" },
    { section: "11", id: "11.07",
      title: "#FreeMathias — hashtag (Depardon campaign)",
      type: "Hashtag archive", producer: "International", date: "May–Jun 2017",
      link: "https://twitter.com/search?q=%23FreeMathias" },
    { section: "11", id: "11.08",
      title: "YouTube — 'Hasankeyf drone' search (post-flooding fly-over archive)",
      type: "Drone video archive", producer: "Multiple content creators", date: "2020+",
      link: "https://www.youtube.com/results?search_query=hasankeyf+drone" },
    { section: "11", id: "11.09",
      title: "YouTube — 'Hasankeyf under water' search",
      type: "Video archive (Turkish)", producer: "Multiple content creators", date: "2019+",
      link: "https://www.youtube.com/results?search_query=hasankeyf+sular+altinda" },
    { section: "11", id: "11.10",
      title: "Wandering Welsh Girl — Hasankeyf 2026 visit guide",
      type: "Travel blog + photo", producer: "Wandering Welsh Girl", date: "2026",
      link: "https://wanderingwelshgirl.com/" },
    { section: "11", id: "11.11",
      title: "Instagram #Hasankeyf — hashtag archive",
      type: "Photo / video archive", producer: "Multiple users", date: "ongoing",
      link: "https://www.instagram.com/explore/tags/hasankeyf/" },
    { section: "11", id: "11.12",
      title: "TikTok 'hasankeyf' archive",
      type: "Short-form video archive", producer: "Multiple users", date: "2020+",
      link: "https://www.tiktok.com/tag/hasankeyf" },

    // ============ 12 POST-FLOODING ============
    { section: "12", id: "12.01",
      title: "Bülent Kılıç / AFP — last-visitor photo set, 23 Feb 2020",
      type: "Multi-source photo gallery", producer: "Bülent Kılıç / AFP", date: "23 Feb 2020",
      link: "https://www.gettyimages.com/" },
    { section: "12", id: "12.02",
      title: "Sertaç Kayar / Reuters — submersion photo set",
      type: "Wire photo set", producer: "Sertaç Kayar / Reuters", date: "Feb 2020",
      link: "https://www.reuters.com/" },
    { section: "12", id: "12.03",
      title: "Eichelmann — 'We have all lost' photo-essay (October 2019)",
      type: "Photo-essay", producer: "Ulrich Eichelmann / MHS", date: "10 Oct 2019",
      link: "https://www.m-h-s.org/en/we-have-all-lost-hasankeyf-is-sinking" },
    { section: "12", id: "12.04",
      title: "Eichelmann — 'Farewell, my last visit to Hasankeyf'",
      type: "Photo-essay", producer: "Ulrich Eichelmann / Riverwatch", date: "2019",
      link: "https://www.riverwatch.eu/" },
    { section: "12", id: "12.05",
      title: "The Atlantic — photo gallery, 8 October 2019",
      type: "Photo-essay (Alan Taylor)", producer: "Alan Taylor (editor)", date: "8 Oct 2019",
      link: "https://www.theatlantic.com/photo/2019/10/photos-moving-ancient-town-higher-ground/599698/" },
    { section: "12", id: "12.06",
      title: "France 24 Observers — bazaar demolition, 25 November 2019",
      type: "Photo-news + civic video", producer: "France 24", date: "25 Nov 2019",
      link: "https://observers.france24.com/en/20191125-turkey-hasankeyf-market-demolish-ilisu-dam" },
    { section: "12", id: "12.07",
      title: "DW (German) — '12,000-year cultural heritage submerged at Hasankeyf'",
      type: "Documentary + news", producer: "Deutsche Welle", date: "Feb 2020",
      link: "https://www.dw.com/" },
    { section: "12", id: "12.08",
      title: "El-Rızk minaret above water — the most circulated image",
      type: "Editorial photo", producer: "Bülent Kılıç (AFP) + Burak Kara (Getty)", date: "Mar–Apr 2020",
      link: "https://www.gettyimages.com/" },
    { section: "12", id: "12.09",
      title: "Medieval bridge piers as waters rise (drone)",
      type: "Drone photo", producer: "AFP + independent", date: "Mar 2020",
      link: "https://www.gettyimages.com/" },
    { section: "12", id: "12.10",
      title: "AA — New Hasankeyf, construction and handover",
      type: "State photo-news", producer: "Anadolu Agency", date: "2018–2020",
      link: "https://www.aa.com.tr/" },
    { section: "12", id: "12.11",
      title: "İHA — post-submersion documentation",
      type: "Wire photo / video", producer: "İhlas News Agency", date: "2019–2020",
      link: "https://www.iha.com.tr/" },
    { section: "12", id: "12.12",
      title: "Yusuf Yavuz — 'They will forcibly evacuate Hasankeyf in 15 days' (Odatv)",
      type: "Photo-news (Turkish)", producer: "Yusuf Yavuz / Odatv", date: "Oct 2019",
      link: "https://odatv4.com/" },

    // ============ 13 POLICY / LEGAL ============
    { section: "13", id: "13.01",
      title: "OECD Watch — Bresser Eurasia complaint dossier (full)",
      type: "Legal document", producer: "Hasankeyf Matters / IKHA / FIVAS / Both ENDS", date: "2017–2018",
      link: "https://www.oecdwatch.org/complaint/hasankeyf-matters-fivas-iniative-to-keep-hasankeyf-alive-and-both-ends-vs-bresser-eurasia/" },
    { section: "13", id: "13.02",
      title: "Hasankeyf Matters — final status of the Bresser complaint",
      type: "Report analysis", producer: "Hasankeyf Matters", date: "Aug 2018",
      link: "https://hasankeyfmatters.com/" },
    { section: "13", id: "13.03",
      title: "Resettlement Action Plan (RAP) — Berne Declaration assessment",
      type: "Independent expert report", producer: "Public Eye / WEED / ECA-Watch", date: "11 Sep 2007",
      link: "https://www.publiceye.ch/" },
    { section: "13", id: "13.04",
      title: "ECHR — Ahunbay application declared inadmissible",
      type: "ECHR ruling", producer: "European Court of Human Rights", date: "5 Mar 2019",
      link: "https://hudoc.echr.coe.int/" },
    { section: "13", id: "13.05",
      title: "BBC — 'Insurers halt work on Turkish dam'",
      type: "News", producer: "BBC", date: "24 Dec 2008",
      link: "https://news.bbc.co.uk/2/hi/business/7798292.stm" },
    { section: "13", id: "13.06",
      title: "IKHA — 'Destruction and Resistance in Hasankeyf and the Tigris' report",
      type: "NGO report", producer: "IKHA / MEM", date: "2019",
      link: "https://www.hasankeyfgirisimi.net/" },
    { section: "13", id: "13.07",
      title: "'Proposed Questions to the Government of Turkey' — dam impacts",
      type: "Rights-based report", producer: "IKHA + CounterCurrent", date: "29 Apr 2010",
      link: "https://www.gegenstroemung.org/" },
    { section: "13", id: "13.08",
      title: "Wikipedia — Ilısu Dam, English-language entry",
      type: "Encyclopaedia", producer: "Wikipedia contributors", date: "current",
      link: "https://en.wikipedia.org/wiki/Il%C4%B1su_Dam" },
    { section: "13", id: "13.09",
      title: "Wikipedia — Hasankeyf",
      type: "Encyclopaedia", producer: "Wikipedia contributors", date: "current",
      link: "https://en.wikipedia.org/wiki/Hasankeyf" },
    { section: "13", id: "13.10",
      title: "Wikipedia — Ilısu Barajı (Turkish-language version)",
      type: "Encyclopaedia (Turkish)", producer: "Wikipedia contributors", date: "current",
      link: "https://tr.wikipedia.org/wiki/Il%C4%B1su_Baraj%C4%B1" },

    // ============ 14 EXHIBITIONS ============
    { section: "14", id: "14.01",
      title: "17th Istanbul Biennial",
      type: "Müze Gazhane, Kadıköy, Istanbul", producer: "Ute Meta Bauer, Amar Kanwar, David Teh (curators)",
      date: "17 Sep – 20 Nov 2022",
      link: "https://17b.iksv.org/" },
    { section: "14", id: "14.02",
      title: "Ecologies of Making Worlds — conference and exhibition",
      type: "Academy of Fine Arts Vienna", producer: "Pelin Tan et al.", date: "Nov 2024",
      link: "https://www.akbild.ac.at/" },
    { section: "14", id: "14.03",
      title: "Spore Hosts: Planetary Design — Reclaiming Futures",
      type: "Spore Initiative, Berlin", producer: "Spore Initiative", date: "2024",
      link: "https://spore-initiative.org/" },

    // ============ 15 HISTORICAL ============
    { section: "15", id: "15.01",
      title: "Albert Gabriel — 'Voyages archéologiques dans la Turquie Orientale' (1940), full text",
      type: "Historical academic photo / drawing", producer: "Albert Gabriel / De Boccard, Paris",
      date: "1940",
      link: "https://archive.org/" },
    { section: "15", id: "15.02",
      title: "SALT Research archive — Hasankeyf / Hisn Kayfa, Ottoman period",
      type: "Historical photo / postcard", producer: "Various Ottoman / Levantine photographers",
      date: "late 19th – early 20th c.",
      link: "https://saltresearch.org/" },
    { section: "15", id: "15.03",
      title: "SALT Research — 'Hisn Kayfa' search",
      type: "Historical archive", producer: "SALT", date: "late 19th c.+",
      link: "https://saltresearch.org/" },
    { section: "15", id: "15.04",
      title: "Library of Congress — historical photographs of Hasankeyf",
      type: "Historical photo", producer: "U.S. Library of Congress", date: "20th c.",
      link: "https://www.loc.gov/" },
    { section: "15", id: "15.05",
      title: "Atatürk Library — historical images of Hasankeyf",
      type: "Historical archive", producer: "İBB Atatürk Library", date: "20th c.",
      link: "https://katalog.ibb.gov.tr/" },
    { section: "15", id: "15.06",
      title: "Wikimedia Commons — 'Old photographs of Hasankeyf' category",
      type: "Historical photo", producer: "Wikimedia users", date: "late 19th – 20th c.",
      link: "https://commons.wikimedia.org/wiki/Category:Old_photographs_of_Hasankeyf" },
    { section: "15", id: "15.07",
      title: "Wikipedia — 'Hasankeyf' historical-photo selection",
      type: "Visual selection", producer: "Wikipedia", date: "current",
      link: "https://en.wikipedia.org/wiki/Hasankeyf" },
    { section: "15", id: "15.08",
      title: "Royal Geographical Society — Gertrude Bell-era travel photographs (region)",
      type: "Historical travel photo", producer: "Gertrude Bell et al.", date: "1900–1920s",
      link: "https://www.rgs.org/" },
    { section: "15", id: "15.09",
      title: "Newcastle University — Gertrude Bell Online Archive",
      type: "Academic historical archive", producer: "Newcastle Univ. / Gertrude Bell", date: "1900–1920s",
      link: "https://gertrudebell.ncl.ac.uk/" },
    { section: "15", id: "15.10",
      title: "Smithsonian Magazine — 'Endangered Site: Hasankeyf' (Andrew Curry, 2009)",
      type: "Photo-essay (pre-modern)", producer: "Andrew Curry / Smithsonian", date: "Mar 2009",
      link: "https://www.smithsonianmag.com/travel/endangered-cultural-treasures-hasankeyf-15292683/" },
    { section: "15", id: "15.11",
      title: "Hasankeyf District Governorship — historical promotional brochures (pre-2015)",
      type: "State brochure", producer: "Hasankeyf District Governorship", date: "1990s–2010s",
      link: "http://www.hasankeyf.gov.tr/" },
    { section: "15", id: "15.12",
      title: "Coşkun Aral archive (artist's personal site)",
      type: "Documentary photo", producer: "Coşkun Aral", date: "1980s+",
      link: "https://www.coskunaral.com/" },
    { section: "15", id: "15.13",
      title: "İzzet Keribar personal site — Hasankeyf series",
      type: "Landscape photo", producer: "İzzet Keribar", date: "1990s–2015",
      link: "https://www.izzetkeribar.com/" },
  ],
};
